# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76650823b34c90d537a33803045fa358b24348bfb407018078cf39e19d307b523364391d27f6ec53eb52226128829906fbfeef3ee86fd1aef67c12f4f7280572

test:
  secret_key_base: cca492483849cef2deb4b84697c815132f79da26ffbf8093eeb8304d2a3fc4a763a463facbbe5dcad28d6b6c93a6250ebd7a69eac66f4df2d8d81cba8e8b623f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
